# Generated by Django 4.2 on 2023-04-21 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('notes', models.TextField(max_length=1000, verbose_name='Pastabos')),
            ],
            options={
                'verbose_name_plural': 'Darbai',
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('position', models.CharField(max_length=100, verbose_name='Pareigos')),
            ],
            options={
                'verbose_name_plural': 'Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('company', models.CharField(max_length=100, verbose_name='Įmonė')),
                ('contacts', models.TextField(max_length=200, verbose_name='Kontaktai')),
            ],
            options={
                'verbose_name_plural': 'Klientai',
            },
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Išrašymo data')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Sąskaitos',
            },
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Įveskite projekto pavadinimą', max_length=200, verbose_name='Pavadinimas')),
                ('start_date', models.DateField(help_text='Įveskite projekto pradžios datą', verbose_name='Projekto pradžios data')),
                ('end_date', models.DateField(help_text='Įveskite projekto pabaigos datą', verbose_name='Projeko pabaigos data')),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.saskaita')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.klientas')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.darbas')),
                ('workers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.darbuotojas')),
            ],
            options={
                'verbose_name_plural': 'Projektai',
            },
        ),
    ]
